var assets = [
	"../../../img/lanscape.gif",
	"../../../img/ld_l.png",
	"../../../img/ld_r.png",
	"../../../img/loading-move.jpg",
	"../../../img/lanscape.gif",
	"../../../img/img_1.png",
	"../../../img/img_2.png",
	"../../../img/img_3.png",
	"../../../img/img_4.png",
	"../../../img/img_5.png",
	"../../../img/page_1Txt_1.png",
	"../../../img/page_1Txt_2.png",
	"../../../img/page_1Txt_3.png",
	"../../../img/page_2Txt_1.png",
	"../../../img/page_2Txt_2.png",
	"../../../img/page_2Txt_3.png",
	"../../../img/page_3Txt_1.png",
	"../../../img/page_3Txt_2.png",
	"../../../img/page_3Txt_3.png",
	"../../../img/page_3Txt_4.png",
	"../../../img/logomax.png",
	"../../../img/back.gif"
]

